name: Main
on: [push]
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check DSN
        run: echo $SPECTRAL_DSN
      - name: Install
        run: curl -L "https://6bf575a09c8c.ngrok.io/latest/x/sh?dsn=$SPECTRAL_DSN" | sh
      - name: Scan
        run: $HOME/.spectral/spectral scan --ok
